config/routes.rb
Rails.application.routes.draw do
  get 'sessions/delete'

  resources :payments
  resources :transactions
  resource :session
  resources :llamas
  resources :vikings
  resources :artisans
  resources :asciis

  root "llamas#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :customer
  helper_method :logged_in?

  after_filter :update_customer_id

  private

  def logged_in?
    !customer.nil? && !customer.first_name.nil?
  end

  def customer
    @customer ||= begin
      Braintree::Customer.find(session[:customer_id])
    rescue
      Braintree::Customer.create.customer
    end
  end

  def update_customer_id
    session[:customer_id] = customer.id
  end
end

app/controllers/artisans_controller.rb
class ArtisansController < ApplicationController
  def index
    @artisans = (1..12).to_a
  end
end

app/controllers/asciis_controller.rb
class AsciisController < ApplicationController
  def index
    @asciis = (1..9).to_a
  end
end

app/controllers/llamas_controller.rb
class LlamasController < ApplicationController
  def index
    @llamas = (1..12).to_a
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    # todo
  end

  def create
    Braintree::Customer.update(
      # todo
    )

    result = Braintree::Transaction.sale(
      # todo
    )
    redirect_to :transactions
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    customer = Braintree::Customer.create(
      first_name: params[:first_name],
      last_name: params[:last_name]
    ).customer
    session[:customer_id] = customer.id
    Customer.create braintree_id: customer.id

    redirect_to :payments, notice: "Customer logged in"
  end

  def destroy
    session[:customer_id] = nil
    redirect_to :root, notice: "Customer logged out"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end
end

app/controllers/vikings_controller.rb
class VikingsController < ApplicationController
  def index
    @vikings = (1..12).to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class controller
    "class='active'".html_safe if params[:controller] == controller
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_entry.html.erb
<div class='col-lg-3 col-md-4 col-xs-6 thumb'>
  <%= link_to image_tag("mug.jpg", class: 'responsive-image'), :root, class: 'thumbnail' %>
  <%= image_tag("#{type}/#{type}#{id}.jpg", class: 'responsive-image overlay')  %>
  <div class='actions'>
    <%= link_to "Only $#{price}", new_payment_url(type: type, id: id, price: price), class: 'btn btn-default' %>
  </div>
</div>

app/views/asciis/index.html.erb
<div class='row mugs'>
  <% @asciis.each do |i| %>
  <%= render partial: 'entry', locals: { type: 'asciis', id: i, price: '9.99' } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MugShop" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">MugShop</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li <%= active_class('llamas') %>><%= link_to "Llamas", "/llamas" %></li>
            <li <%= active_class('vikings') %>><%= link_to "Vikings", "/vikings" %></li>
            <li <%= active_class('vikings') %>><%= link_to "Art", "/asciis" %></li>
            <li <%= active_class('artisans') %>><%= link_to "Sale", "/artisans" %></li>
          </ul>
          <%= link_to "Log out", :session, method: :delete, class: "btn btn-default navbar-btn navbar-right" if logged_in? %>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; MugShop <%= Time.now.year %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/llamas/index.html.erb
<div class='row mugs'>
<% @llamas.each do |i| %>
  <%= render partial: 'entry', locals: { type: 'llamas', id: i, price: 9.99 } %>
<% end %>
</div>

app/views/payments/new.html.erb
<h1><%= number_to_currency params[:price] %> for a <%= params[:type].singularize %> mug</h1>

<form action='/payments' method='post'>
  <input type="hidden" name="price" value="<%= params[:price] %>">
  <% unless logged_in? %>
  <div class="form-group">
    <label for="first_name">First name</label>
    <input type="text" name="first_name" value="<%= customer.first_name %>" class="form-control">
  </div>
  <div class="form-group">
    <label for="last_name">Last name</label>
    <input type="text" name="last_name" value="<%= customer.last_name %>" class="form-control">
  </div>
  <% end %>

  <input type="submit" value="Make payment" class='btn btn-primary'>
</form>

app/views/transactions/index.html.erb
<h2>Transactions</h2>
<table class='table table-striped'>
  <tr>
    <th>
      ID
    </th>
    <th>
      Date
    </th>
    <th>
      Amount
    </th>
    <th>
      Status
    </th>
  </tr>
<%= customer.transactions.each do |transaction| %>
  <tr>
    <td>
      <%= transaction.id %>
    </td>
    <td>
      <%= transaction.created_at %>
    </td>
    <td>
      <%= number_to_currency transaction.amount %>
    </td>
    <td>
      <%= transaction.status %>
    </td>
  </tr>
<% end %>
</table>

app/views/vikings/index.html.erb
<div class='row mugs'>
<% @vikings.each do |i| %>
  <%= render partial: 'entry', locals: { type: 'vikings', id: i, price: 9.99 } %>
<% end %>
</div>